# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170125_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='birth_date',
            field=models.DateTimeField(verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
