# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170125_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown'),
        ),
    ]
