# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170126_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', null=True),
        ),
    ]
