# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170404_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0725, max_digits=8),
        ),
    ]
