# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170407_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='tax',
            field=models.DecimalField(decimal_places=4, default=0.0725, max_digits=8),
        ),
    ]
