# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_shoppingcart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_shipping',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
        ),
    ]
