# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_shoppingcart_total_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
